version: '2'

services: 
  blob:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
     - "10000:10000"
     - "10001:10001"
  
  sample:
    build:
      context: ./sample-service
      dockerfile: Dockerfile
    depends_on: 
     - blob